@startuml joiningPool
actor Owner #Red
actor Borrower #Green
actor PoolParticipants

Borrower -> LoanFactory : **createLoanToken**
activate LoanFactory
LoanFactory <- LoanFactory : checks if //amount// and //term// are greater than 0

LoanFactory -> LoanToken : create new instance of **LoanToken**
activate LoanToken
LoanFactory <- LoanFactory : add created **LoanToken** address to existing tokens mapping
LoanFactory <-- LoanToken
deactivate LoanToken

Borrower <-- LoanFactory
deactivate LoanFactory

Owner -> TrueRatingAgency : **allow** Borrower for submitting
activate TrueRatingAgency
TrueRatingAgency <- TrueRatingAgency : **add** Borrower to //allowedSubmitters//
Owner <-- TrueRatingAgency
deactivate TrueRatingAgency

Borrower -> TrueRatingAgency : **submit** **LoanToken**
activate TrueRatingAgency
TrueRatingAgency <- TrueRatingAgency : check if Borrower is in //allowedSubmitters//

TrueRatingAgency -> LoanFactory : check if **LoanToken** is created by **LoanFactory**
activate LoanFactory
LoanFactory <- LoanFactory : checks if //isLoanToken//
TrueRatingAgency <-- LoanFactory
deactivate LoanFactory

Borrower <-- TrueRatingAgency
deactivate TrueRatingAgency

break when Borrower wants to retract
    Borrower -> TrueRatingAgency : **retract** **LoanToken**
    activate TrueRatingAgency
    TrueRatingAgency <- TrueRatingAgency : checks if Borrower created **LoanToken**
    TrueRatingAgency <- TrueRatingAgency : deletes LoanToken from **TrueRatingAgency**
    Borrower <-- TrueRatingAgency
    deactivate TrueRatingAgency
    end

PoolParticipants -> TrueRatingAgency : vote **yes/no** with stakes for **LoanToken**
activate TrueRatingAgency
TrueRatingAgency <- TrueRatingAgency : add votes to the pool
PoolParticipants <-- TrueRatingAgency
deactivate TrueRatingAgency

opt when PoolParticipant wants to withdraw some/all votes
    PoolParticipants -> TrueRatingAgency : withdraw stakes **yes/no** votes
    activate TrueRatingAgency
    TrueRatingAgency <- TrueRatingAgency : remove votes from the pool
    PoolParticipants <-- TrueRatingAgency
    deactivate TrueRatingAgency
    end


@enduml