@startuml joiningPool
actor Owner #Red
actor Borrower #Green
actor TruHolders

Borrower -> LoanFactory : **createLoanToken**
activate LoanFactory
LoanFactory <- LoanFactory : checks if //amount// and //term// are greater than 0

LoanFactory -> LoanToken : create new instance of **LoanToken**
activate LoanToken
LoanFactory <- LoanFactory : add created **LoanToken** address to existing tokens mapping
LoanFactory <-- LoanToken
deactivate LoanToken

Borrower <-- LoanFactory
deactivate LoanFactory

Owner -> TrueRatingAgency : **allow** Borrower for submitting
activate TrueRatingAgency
TrueRatingAgency <- TrueRatingAgency : **add** Borrower to //allowedSubmitters//
Owner <-- TrueRatingAgency
deactivate TrueRatingAgency

Borrower -> TrueRatingAgency : **submit** **LoanToken**
activate TrueRatingAgency
TrueRatingAgency <- TrueRatingAgency : check if **status** is //void//
TrueRatingAgency <- TrueRatingAgency : check if Borrower is in //allowedSubmitters//

TrueRatingAgency -> LoanFactory : check if **LoanToken** is created by **LoanFactory**
activate LoanFactory
LoanFactory <- LoanFactory : checks if in //isLoanToken//
TrueRatingAgency <-- LoanFactory
deactivate LoanFactory

Borrower <-- TrueRatingAgency
deactivate TrueRatingAgency

break when Borrower wants to retract
    Borrower -> TrueRatingAgency : **retract** **LoanToken**
    activate TrueRatingAgency
    TrueRatingAgency <- TrueRatingAgency : checks if **status** is //pending//
    TrueRatingAgency <- TrueRatingAgency : checks if Borrower created **LoanToken**
    TrueRatingAgency <- TrueRatingAgency : deletes LoanToken from **TrueRatingAgency**
    Borrower <-- TrueRatingAgency
    deactivate TrueRatingAgency
    end

TruHolders -> TrueRatingAgency : vote **yes/no** with stakes for **LoanToken**
activate TrueRatingAgency
TrueRatingAgency <- TrueRatingAgency : check if **status** is //pending//
TrueRatingAgency <- TrueRatingAgency : add vote stakes to votes and predictions
TruHolders <-- TrueRatingAgency
deactivate TrueRatingAgency

opt when PoolParticipant wants to withdraw some/all votes
    TruHolders -> TrueRatingAgency : **withdraw** staked **yes/no** votes
    activate TrueRatingAgency
    TrueRatingAgency <- TrueRatingAgency : check if **status** is __not__ //running//
    TrueRatingAgency <- TrueRatingAgency : remove vote stakes from votes and predictions
    TruHolders <-- TrueRatingAgency
    deactivate TrueRatingAgency
    end



@enduml