@startuml joiningPool
actor PoolParticipant

PoolParticipant -> TUSD : **approve** TrueFiPool
activate TUSD
PoolParticipant <-- TUSD
deactivate TUSD

PoolParticipant -> TrueFiPool : **join** pool with //amount//
activate TrueFiPool
TrueFiPool <- TrueFiPool : calculate //fee//

TUSD <- TrueFiPool : **transferFrom** (//amount//) PoolParticipant's balance to the Pool
activate TUSD
TUSD <- TUSD : checks **allowance**
TUSD <- TUSD : performs **transfer**
TUSD --> TrueFiPool
deactivate TUSD

TrueFiPool <- TrueFiPool : **add** (//fee//) to //claimableFees//
TrueFiPool <- TrueFiPool : **mint** (//amount// - //fee//) pool tokens to PoolParticipant's balance
PoolParticipant <-- TrueFiPool
deactivate TrueFiPool
@enduml